# made by kjh9211
# made in artiste
on tab completer for "/스코어보드":
	#In this line we need to put the command.
	set {_completers::*} to "켜기" and "끄기"
	#In this line we need to put the arguments to complete.
	loop {_completers::*}:
		add loop-value to completions
# if you use /스코어보드, plz enable that command line

on tab completer for "/rank":
	set {_completers::*} to "add", "remove", "view", "익스트림", "베이직", player and "프리미엄"
	loop {_completers::*}:
		add loop-value to completions
